//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public long idPaciente { get; set; }
        public long idRegClinico { get; set; }
        public System.DateTime fecha { get; set; }
        public int nroSala { get; set; }
        public int nroCama { get; set; }
        public string diagnostico { get; set; }
        public string observacion { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
